import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import navbar from "@/composants/navbar";
import Paragraphe from "@/composants/paragraphe";

const inter = Inter({ subsets: ["latin"] });

export default function about_page() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <div className={styles.logonavbar}>
          <Image className={styles.logonavbar} src="/pikachu.png" alt="pikachu Logo" width={60} height={60} priority />
        </div>
        {navbar()}
      </nav>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.bloc_card}>{Paragraphe("Mon parcours", "Bachelor - Responsable de Projets Informatiques école ISITECH LYON octobre 2022 à octobre 2025 cycle en alternance sur 3 ans, Baccalauréat général spécialités Mathématique et Physique Chimie Lycée Sacré Coeur juillet 2022")}</div>
        <div className={styles.bloc_card}>{Paragraphe("Experience professionelle", "Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en soit modifié. Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker. ")}</div>
      </main>
    </>
  );
}
