import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import navbar from "@/composants/navbar";
import stylescontact from "@/styles/Contact.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function about_page() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <div className={styles.logonavbar}>
          <Image className={styles.logonavbar} src="/pikachu.png" alt="pikachu Logo" width={60} height={60} priority />
        </div>
        {navbar()}
      </nav>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={stylescontact.container}>
          <div className={stylescontact.contact}>
            <h3>Contactez-nous</h3>
            <label>
              Prenom <input type="text" />
            </label>
            <label>
              Nom <input type="text" />
            </label>
            <label>
              Email <input type="text" />
            </label>
            <label>
              Message <textarea></textarea>
            </label>
            <button>Send</button>
          </div>
        </div>
      </main>
    </>
  );
}
