import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Bonjour from "@/composants/bonjour";
import navbar from "@/composants/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.navbar}>
        <div className={styles.logonavbar}>
          <Image className={styles.logonavbar} src="/pikachu.png" alt="pikachu Logo" width={60} height={60} priority />
        </div>
        {navbar()}
      </nav>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.sectionPrincipal}>
          <div className={styles.sectionTexte}>
            <a>
              <h1 className={styles.titrePrincipal}>Hi!</h1>
              <h1 className={styles.titrePrincipal}>
                I'am <span className={styles.textecouleur}>Matéo</span>
              </h1>
              <h1 className={styles.titrePrincipal}>Web developer</h1>
              <button className={styles.contactButton}>Contact</button>
            </a>
          </div>
          <div className={styles.sectionTexte}>
            <Image className={styles.logonavbar} src="/pikachu.png" alt="pikachu Logo" width={300} height={300} priority />
          </div>
        </div>
      </main>
    </>
  );
}
